import Image from 'next/image';
import React from 'react';

export const metadata = {
  title: "Waliullah | About Us",
  description: "Generated by create next app",
};

const AboutPage = () => {
    return (
        <div>
            <h2>Our About Section here</h2>
            <Image src="/nature.jpg" width={300} height={300} alt='Nature'></Image>
            <Image src="/waliullah.jpg" width={300} height={300} alt='Waliullah'></Image>
            <Image src="/flower1.jpg" width={300} height={300} alt='Flower1'></Image>
            <Image src="/flower2.jpg" width={300} height={300} alt='Flower2'></Image>
            <Image src="https://plus.unsplash.com/premium_photo-1790818072067-537bcece1069" width={300} height={300} alt='Flower2'></Image>
        </div>
    );
};

export default AboutPage;